### ISSUE TITLE
Conversion of Szczecinek

### ISSUE THREAD

**Issue by wsc44** [GrandOrgue/OdfEdit#50] opened 2024-04-20 16:24 UTC
Thanks for version V.11 and for keeping up the good work! - I converted Peter Grabowskis Szczecinek. The free combinations, reeds off and Registratur Absteller work as expected. A nice improvement compared to the standard GO-Odf delivered by Peter Grabowski! - Something must go wrong with the fixed combinations. As I can see in the .org file they are integrated somehow but do not work as expected. If I select stops manually and push one of the fixed combination buttons organ sound stops immediately, if I push again sounds back again. That way they mimic the Registratur Absteller. Would be a huge step forward if one could generate an ODF with fixed combinations working as they should.
Another topic: All the noise-files get packed into the pedal windchest/enclosure. So there is no way to regulate the noise level. Please have a look into these matters.

**Comment by eturpault** [comment] 2024-04-20 18:14
I have done the test. Indeed there is an issue with the conversion of the switches controlling the fixed combinations, they are created twice (one for each panel Console and Stops) in the GO ODF. I will analyze and fix it.

About the noise files, in the HW ODF they are actually all linked to the same windchest "Wiatrownica P" which has no enclosure attached to it. There is an enclosure defined only for the windchest "Wiatrownica II" for the Manual II. So OdfEdit has converted correctly what is defined in the HW ODF.
In the ODF generated by OdfEdit, you can move the noise Stop sections inside a decidated WindchestGroup section which will you be able to control the audio level in the GO menu. Here are the steps :
- select the Organ section then click on the "Add" button. In the shown list select WindchestGroup and click OK. This will create a new WindchestGroup section WindchestGroup004, give it the name "Noises" for example.
- select the created WindchestGroup004 section then click on the "Children" button. In the shown list **select** all the 118 Stop sections which the name ends by "noise".
- select the WindchestGroup001 (Wiatrownica P) section then click on the "Children" button. In the shown list, **unselect** all the same 118 Stop sections.

Now all the noise Stop sections are linked to the WindchestGroup004 and no more to the WindchestGroup001, and in the menu "Organ settings" in GO you will be able regulate the gain of the windchest "Noises".

**Comment by wsc44** [comment] 2024-04-21 01:05
Thanks for your prompt (!) answer. So far I haven't used the edit-function of OdfEdit. Will try out your suggestions tomorrow. - Looking forward to an updated OdfEdit-version with improved switch network capability. Such a complex matter will take some time, but I'm sure it will be worth the waiting ...

**Comment by eturpault** [comment] 2024-04-24 21:44
I have understood why fixed combinations are not working in this sample set. It is because they need to be converted into General sections in the GO ODF, and currently OdfEdit does not manage the generation of the such sections. 
I am going to implement this evolution for next OdfEdit version.
Thank you @wsc44 for having highlighted this sample set, it is a very interresting and complete one in term of evoluted switches networks and combinations (fixed and free), and thus will permit OdfEdit to be improved.

**Comment by eturpault** [comment] 2024-04-26 20:13
@wsc44 Here is a first version of the Szczecinek GO ODF where the fixed combinations are supported. I have some optimisations to do in the ODF generation, but the functionnaly it is ok. What do you think about it ?
[Szczecinek.zip](https://github.com/GrandOrgue/OdfEdit/files/15134759/Szczecinek.zip)

Finally I didn't used General sections, I used standard switches, it fits better with the HW ODF implementation. Combinations buttons are not exclusive between them (as they are in HW I think looking at how the HW ODF is set), but as far as I know GO ODF syntax has no feature to have like radio buttons.

**Comment by wsc44** [comment] 2024-04-27 17:30
I like it. Pity of course that GO doesn't provide objects like radio-button and I miss that functionality, but still it is a nice improvement.

I wonder if the manuals are coupled in HW too when the "piano"-button is pushed. At least I didn't expect coupling for the piano-combination, but who knows. I wouldn't even bet that these fixed combinations are the "real" ones. I doubt very much that Peter Grabowski took the time to check the tube wirings ... and if he had permission to do such thing in the first place.

Another item: I cannot find something like "Known issues" for OdfEdit, be it on github (Did I miss something?) nor in the help file.
No radio-button-functionality (as in Szczecinek, due to GO-limitations) or detune-functionality would be candidates for such a list.

**Comment by oleg68** [comment] 2024-04-27 18:20
GO **supports** radio-buttons in General and Divisional sections. So using them is the right way of implementing fixing combinations.

Both General and Divisional may involve not only the stops but also switches.

**Comment by eturpault** [comment] 2024-04-27 19:46
As you confirm it is not possible to simulate radio buttons with Switch sections, I will come back to my initial plan which was to use General sections, controlling switches.

**Comment by eturpault** [comment] 2024-05-21 23:18
I implemented the conversion from HW Combination sections to GO General / Divisional sections.
General and Divisional sections contain only references to Switch sections.
I get an error when loading the generated ODF in GrandOrgue with Division sections.
The error message is : **Error: Out of range value at section 'Divisional101' entry 'Switch014': -15**
The Divisional101 section is defined as follows :

[Divisional101]
Name=HW cancel
Protected=Y
NumberOfCouplers=0
NumberOfStops=0
NumberOfTremulants=0
NumberOfSwitches=14
Switch001=-002
Switch002=-003
Switch003=-004
Switch004=-005
Switch005=-006
Switch006=-007
Switch007=-008
Switch008=-009
Switch009=-010
Switch010=-011
Switch011=-012
Switch012=-013
Switch013=-014
Switch014=-015

The section Switch015 is defined in the ODF and is referenced in the Manual001 section in which is referenced the Divisional101 section.
The Switch015 is controlling a Tremulant001 section, also referenced in Manual001.
If I remove the line Switch014=-015 (and I set NumberOfSwitches=13) the error disappears (and appears in the next Divisional102 section of the Manual).
If I place the reference to Switch015 for example in line : Switch007=-015, the errors becomes :
**Error: Out of range value at section 'Divisional101' entry 'Switch007': -15**

Here is the full ODF : [Lorris_wet_and_dry.zip](https://github.com/GrandOrgue/OdfEdit/files/15396189/Lorris_wet_and_dry.zip)

@oleg68 @larspalo : Which issue this message can be pointing out according to you ?
Is it due to the fact that this switch is controlling a Tremulant ?
The reference to this switch in the General sections is not causing an error.

**Comment by larspalo** [comment] 2024-05-22 07:26
@eturpault It's a _very common_ mistake made when using the old style odf divisionals. The listed switches in the divisionals should _not be the global switch number_, **but instead the number of the switch as listed on the manual**. Since you're requesting switch number 15 with -015, but the manual only has 14 switches - it's obviously out of range.

So, quickly looking at the Manual001, the [Switch015] (Tremulant) is listed as Switch014 in the manual. To control that (Tremulant Switch015) from an old style divisional, you add the -014 there as _that's the listed switch on that manual_.

In https://github.com/GrandOrgue/grandorgue/discussions/1349, where both you and the topic starter misunderstood the referencing and logic for old style odf divisionals and switches, the correct way is shown. So, do note that you might not get the actual switch in the odf divisional that you think you're referencing!

**Comment by eturpault** [comment] 2024-05-22 21:27
Indeed... I totally forgot this rule, thank for having reminded it. Now I have no more ODF loading error after having implemented correctly the switches referencing in Division sections.

In the Szczecinek ODF, the fixed combinations (Registratur Absteller, Piano, Mezzoforte, Forte, Tutti) are now converted by OdfEdit in protected General sections, with exclusive buttons states between them as expected.
It remains the free combinations (Freie Combination 1, Freie Combination 2) which cannot be converted in General sections because they are conditional switches controlling the two alternate ranks of drawstops, so they are not disengaging the fixed combinations buttons when they are engaged (and vice-versa), as it is defined in the HW ODF.
Another side effect of the difference of buttons type between fixed and free combinations is that for having a fixed combination to be applied, a free combination button has to be engaged. This is a consequence of how these buttons are linked between them in the HW ODF.
![Szczecinek combinations](https://github.com/GrandOrgue/OdfEdit/assets/51839171/bd226a57-6361-476b-981a-c54b4d0e0d0a)

**Comment by larspalo** [comment] 2024-05-23 07:07
@eturpault You're very welcome!

I helped Mark create such an old type of combination system for the Ta'xbiex sample set. The method used is detailed in https://github.com/GrandOrgue/GoOdf/discussions/35#discussioncomment-6520846 and you can of course ask @Bumblebee001 for the sample set to inspect the full working version. It's however a somewhat complex setup. If you find another way of implementing it I'd be interested in learning it.

**Comment by eturpault** [comment] 2024-06-14 13:42
@larspalo : I have had a look at the schematic image that you drawn, it is indeed a tricky switches network, I don't see how I could implement it with OdfEdit from an HW ODF.

Thinking again about this problem, the need is to have the following buttons mutually exclusive : Registratur Absteller, Freie Comb. 1, Freie Comb. 2, Piano, Mezzoforte, Forte and Tutti.
All buttons but the two Freie Comb. can be easily managed using GC button for Registratur Absteller and General buttons for the fixed combinations Piano, Mezzoforte, Forte, Tutti (as it is already done by OdfEdit 2.12). 
The two Freie Comb. buttons are converted to switches by OdfEdit 2.12 (acting on other switches with AND function). They could be converted to General buttons to have the mutual exclusive feature, and these General sections would engage the switch of the corresponding free combination and disengage the switch of the other free combination. General sections of fixed combinations would disengage the two free combination switches.
I hope I was clear in my explanation.
What do you think about this way to do ?

Now I have to think about how to implement it with OdfEdit.

**Comment by larspalo** [comment] 2024-06-14 19:32
@eturpault I've only tested the original GO version of this sampleset where this feature is not at all working. But it would be interesting testing this with the OdfEdit converted versions when it's ready!

I'm not so sure that GC would work so well for the Registratur Absteller if that's instead supposed to return current stop control to the main drawstop items! But all the Registratur Absteller, Comb 1 and Comb 2 should be possible to implement as (fixed content) generals that in turn are acting on switches that mutually exclusively decide which set of stop activators should currently be controlling the back end stops/ranks. I've got much too much to do right now to re-visit this kind of old style combination system, but it will be interesting to see what you can come up with!

**Comment by eturpault** [comment] 2024-06-15 22:20
Here is an ODF that I modified manually (based on the one generated by OdfEdit) to reflect the logic which is implemented in the HW ODF, and which is giving the expected behavior I think concerning the drawstops and combinations effects.
[Szczecinek-test.zip](https://github.com/user-attachments/files/15855417/Szczecinek-test.zip)

- There is one General section defined for each free / fixed combination and for "Registratur Absteller"
- Each General section has one switch permitting to reflect its status (selected / not selected). When one General is selected it engages its own status switch and disengages the status switch of the other Generals, and it sets the status of the drawstops depending on its assigned effect.
- A switch called "Status: AnyCombSelected" is engaged if at least one free / fixed combination status switch is engaged
- The status switches of the Free combinations are conditional switches applying the rows of free combination drawstops
- The main drawstops are applied if the AnyCombSelected switch is disengaged (which could have been rather when the "Registratur Absteller" switch is engaged, but Piotr Grabowski has not done like this)
So the key point in this logic is to have switches permitting to know the status of the Generals, and to use appropriately the status of these switches.

I have now to find how to convert this logic automatically with OdfEdit, which is not trivial...

**Comment by eturpault** [comment] 2024-08-01 16:44
After several attempts I don't see how to convert automatically with OdfEdit the fixed and free combinations and associated switches or push buttons of this sample set. So I stop to try to support the conversion of this with OdfEdit. I can be done manually as I did in the ODF attached to the previous comment.

**Closed** 2024-08-01 16:44 UTC
