### ISSUE TITLE
OdfEdit freezes when converting the BIS Romsey demo

### ISSUE THREAD

**Issue by pgwid-og** [GrandOrgue/OdfEdit#44] opened 2024-02-14 09:33 UTC
Let me start saying thank you for sharing this wonderful tool here on GitHub. I wish I could have made use of this years ago when I struggled preparing my first custom ODFs, using Excel-Spreadsheets (though it was good fun, too!).

One of the HW-ODF I tried to convert the BIS Romsey demo (https://www.beautyinsound.co.uk/products/romsey-abbey-demo-free). OdfEdit-v2.9 just freezes (no error message shown) when building a coupler, cf.
![grafik](https://github.com/GrandOrgue/OdfEdit/assets/159999473/6502e730-d1f1-4172-b7ad-b7780ec6cedc)

As a work-around I deleted the couplers in the HW-ODF, so I could convert it into a GO-ODF, but you might want to investigate this issue yourself. 

P.S. In case others would like to have a look at the BIS Romsey demo: The samples don't have pitch information provided. So one couldn't alter the temperament in GO. Some pictures are not in the correct format to be used by GO.  Besides that it is a nice little English organ (and we don't have too many of them yet in GO).

**Comment by eturpault** [comment] 2024-02-14 09:46
Thanks for this report, there is certainly an error in Python when executing the conversion SW with these couplers, I will look at it and do a fix.

**Comment by eturpault** [comment] 2024-02-14 21:44
I found the reason of the issue : a variable used but not defined before, basic error... It was caused by 12 couplers which are defined in the HW ODF without having associated image defined, so they cannot be controlled. It will be fixed in next OdfEdit version.
There was an issue in OdfEdit caused by missing images for a volume slider (which uses Hauptwerk embedded standard images), it will be fixed in next OdfEdit version.
Strangely the keys of the keyboards and the pedal are all transparent images, so one cannot see the keys moving on the console.
Here is the ODF generated after the fixes described above : [BIS Organs - Romsey Abbey Demo.zip](https://github.com/GrandOrgue/OdfEdit/files/14288771/BIS.Organs.-.Romsey.Abbey.Demo.zip)

Thank you for your kind words about OdfEdit, it encourages me to continue to improve it. I'm glad people are using it.

**Comment by pgwid-og** [comment] 2024-02-15 06:08
Lovely, thank you for your quick response. I tried your Romsey-ODF on my computer and (besides those warnings) it nearly worked perfect (I just ha to replace the "..\SilentLoop.wav" (which are missing) through "DUMMY"!

**Comment by eturpault** [comment] 2024-02-15 08:56
OdfEdit automatically adds the file SilentLoop.wav in the root folder of the sample set (where are the folders OrganDefinition and OrganInstallationPackages) when doing the HW to GO conversion. You can recover it [here](https://github.com/GrandOrgue/OdfEdit/blob/main/src/resources/SilentLoop.wav) and place it manually at the root folder of this sample set. Replacing it by DUMMY in the ODF you are losing the keys release and stops disengage noises.

**Comment by eturpault** [comment] 2024-03-18 21:29
Fixed in OdfEdit v2.10. In addition the extended notes at the upper part of the keyboards are correctly retuned with v2.10.

**Closed** 2024-03-26 19:54 UTC
